import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Question } from '../../features/exam/store';

export class PDFGenerator {
    private doc: jsPDF;
    private readonly margin = 15;
    private readonly pageWidth: number;
    private readonly pageHeight: number;

    constructor() {
        this.doc = new jsPDF();
        this.pageWidth = this.doc.internal.pageSize.width;
        this.pageHeight = this.doc.internal.pageSize.height;
    }

    private addHeader(title: string, subTitle?: string) {
        this.doc.setFillColor(79, 70, 229); // Indigo 600
        this.doc.rect(0, 0, this.pageWidth, 40, 'F');

        this.doc.setTextColor(255, 255, 255);
        this.doc.setFontSize(24);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(title, this.margin, 20);

        if (subTitle) {
            this.doc.setFontSize(12);
            this.doc.setFont('helvetica', 'normal');
            this.doc.text(subTitle, this.margin, 30);
        }

        this.doc.setFontSize(10);
        this.doc.text("Generated by NEURO EXAM", this.pageWidth - this.margin - 45, 20);
        this.doc.text(new Date().toLocaleDateString(), this.pageWidth - this.margin - 25, 30);
    }

    private addFooter(pageNumber: number, totalPages?: number) {
        const str = `Page ${pageNumber}` + (totalPages ? ` of ${totalPages}` : '');
        this.doc.setFontSize(8);
        this.doc.setTextColor(150);
        this.doc.text(str, this.pageWidth / 2, this.pageHeight - 10, { align: 'center' });
    }

    public generate(questions: Question[], title: string = "Exam Questions") {
        this.addHeader(title, `${questions.length} Questions`);

        let y = 50;
        const pageHeight = this.pageHeight;
        const textWidth = this.pageWidth - (this.margin * 2);

        questions.forEach((q, index) => {
            // Check space
            if (y > pageHeight - 40) {
                this.doc.addPage();
                y = 20; // Reset Y
            }

            // Question Header
            this.doc.setFontSize(11);
            this.doc.setTextColor(0, 0, 0); // Black
            this.doc.setFont('helvetica', 'bold');
            this.doc.text(`Q${index + 1}.`, this.margin, y);

            // Question Text
            this.doc.setFont('helvetica', 'normal');
            const splitQuestion = this.doc.splitTextToSize(q.question, textWidth - 10);
            this.doc.text(splitQuestion, this.margin + 10, y);
            y += (splitQuestion.length * 5) + 3;

            // Options
            q.options.forEach((opt: string, optIndex: number) => {
                if (y > pageHeight - 20) {
                    this.doc.addPage();
                    y = 20;
                }
                const label = String.fromCharCode(65 + optIndex);
                this.doc.setTextColor(80);
                this.doc.setFontSize(10);
                const optText = `(${label}) ${opt}`;
                const splitOpt = this.doc.splitTextToSize(optText, textWidth - 12);
                this.doc.text(splitOpt, this.margin + 12, y);
                y += (splitOpt.length * 4.5);
            });

            y += 6; // Spacing between questions
        });

        // --- ANSWER KEY SECTION ---
        this.doc.addPage();
        this.addHeader("Answer Key & Explanations");

        const tableData = questions.map((q, i) => [
            (i + 1).toString(),
            String.fromCharCode(65 + q.correctAnswer),
            q.explanation || 'No explanation provided.'
        ]);

        autoTable(this.doc, {
            startY: 50,
            head: [['Q', 'Ans', 'Explanation']],
            body: tableData,
            styles: { fontSize: 9, cellPadding: 3 },
            headStyles: { fillColor: [79, 70, 229] },
            columnStyles: {
                0: { cellWidth: 15 }, // Q
                1: { cellWidth: 15 }, // Ans
                2: { cellWidth: 'auto' } // Explanation
            },
            alternateRowStyles: { fillColor: [245, 247, 255] },
            margin: { top: 50, left: this.margin, right: this.margin }
        });

        // Add page numbers
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const pageCount = (this.doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);
            this.addFooter(i, pageCount);
        }

        this.doc.save(`${title.replace(/\s+/g, '_')}_NeuroExam.pdf`);
    }
}
